DATALOADER:
  PATH: "./data"
  DATANAME: "cifar10" # cifar10 or cifar100
  BATCH_SIZE: 128 # original paper does not specify, we use default value in research field

INPUT:
  SIZE: [32, 32]
  PIXEL_MEAN: [0.4914, 0.4822, 0.4465]
  PIXEL_STD: [0.2023, 0.1994, 0.2010] # obtained from imagenet

OUTPUT:
  DIR: ""

SEED: 0

OPTIM:
  LR: 0.1
  MAX_EPOCH: 100
  LR_SCHEDULER: "step"
  LR_MILESTONES: [150, 225]
  LR_DECAY: 0.2
  PART_RATE: 0.1
  PREC: 'fp16'
  WEIGHT_DECAY: 5e-4 # for FocusedDropout, we need to put higher weight decay as paper demonstrated
  DROP_RATE: 0.3
  DROP_METHOD: ""
  BLOCK_SIZE: 7 # default

MODEL:
  BACKBONE: "resnet20" # resnet20/resnet56/resnet110/vgg19/densenet100/wrn28
