DATALOADER:
  PATH: "./data"
  DATANAME: "cifar10" # cifar01 or cifar100
  BATCH_SIZE: 32 # original paper does not specify, we use default value in research field

INPUT:
  SIZE: [32, 32]
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073] # obtained from imagenet
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711] # obtained from imagenet

OUTPUT:
  DIR: ""

SEED: 0

OPTIM:
  NAME: "sgd"
  LR: 0.02
  MAX_EPOCH: 1
  LR_SCHEDULER: "step"
  LR_MILESTONES: [150, 225]
  LR_DECAY: 0.1
  PART_RATE: 0.1
  WEIGHT_DECAY: 1e-3 # for FocusedDropout, we need to put higher weight decay as paper demonstrated
  DROP_RATE: 0.3
  DROP_METHOD: ""
  BLOCK_SIZE: 7 # default

MODEL:
  BACKBONE: "resnet20" # resnet20/resnet56/resnet110/vgg19/densenet100/wrn28
